workspace:
  base: /usr/src/project
  path: .

pipeline:
  build:  # Build
    image: node
    commands:
        - npm i
        - npm run dist
  publish:  # Build image and publish to private registry
    image: plugins/docker
    registry: http://registry.happyrecord.cn:5000
    repo: registry.happyrecord.cn:5000/sunjp123/share
    #secrets: [ docker_username, docker_password ]
    dockerfile: ./cicd/Dockerfile
    default_tags: true
  deploy: 
    image: appleboy/drone-ssh
    host:
        happyrecord.cn
    username: root
    port: 22
    secrets: [ ssh_key ]
    command_timeout: 1200s
    script:
        - cd /usr/src/project
        - /bin/bash run.sh
    
