workspace:
  base: /usr/src/project
  path: .

pipeline:
  build:  # Build go app and package source files
    image: node
    commands:
        - npm i
        - npm run dist
  publish:  # Build image and publish to private registry
    image: plugins/docker
    repo: sunjp123/share
    secrets: [ docker_username, docker_password ]
    dockerfile: ./cicd/Dockerfile
    default_tags: true
  deploy: 
    image: appleboy/drone-ssh
    host:
        happyrecord.cn
    username: root
    port: 22
    secrets: [ ssh_password ]
    script:
        - cd /usr/src/project
        - /bin/bash run.sh
    
