export const UPDATE_EXTEND_INFO = "F_SHARE_UPDATE_EXTEND_INFO"
export const SAVE_SHARE_CATEGORY = "F_SHARE_SAVE_SHARE_CATEGORY"
export const INIT_DATA = "F_SHARE_INIT_DATA"
export const SAVE_SHARE_ITEM = "F_SHARE_SAVE_SHARE_ITEM"