const REDIS_MESSAGE = {
    SHARE_MESSAGE:{
        KEY:'SHARE_MESSAGE_KEY',
        EVENT:'SHARE_MESSAGE_EVENT',
        CONTENT:'%USER% %OPERATE% %CONTENT%'
    }
}

exports.REDIS_MESSAGE = REDIS_MESSAGE